#import <Foundation/Foundation.h>
#import "VGoods_Base_All.h"
@interface LSModel_VGoods_FatherCategory_Play_Extend : LSModel_VGoods_Base_All
@property (nonatomic)NSInteger play_id;
@property (nonatomic)NSInteger play_gsid;
@property (nonatomic)NSInteger play_peoplecount;
@property (nonatomic)NSInteger play_type;
@property (strong,nonatomic) NSString *play_extend;
@property (nonatomic)NSInteger play_whocan;
//@property (nonatomic)NSInteger gs_id;
//@property (strong,nonatomic) NSString *gs_name;
//@property (nonatomic)NSInteger gs_type;
//@property (nonatomic)NSInteger gs_spid;
//@property (nonatomic) float gs_price;
//@property (strong,nonatomic) NSString *gs_desc;
//@property (nonatomic)NSInteger gs_level;
//@property (strong,nonatomic) NSString *gs_smpledesc;
//@property (strong,nonatomic) NSString *gs_smallpic;
//@property (strong,nonatomic) NSString *gs_bigpic;
//@property (strong,nonatomic) NSString *gs_pics;
//@property (nonatomic)NSInteger gs_stock;
//@property (nonatomic)NSInteger gs_score;
//@property (strong,nonatomic) NSString *gs_extend;
//@property (nonatomic)NSInteger gs_keeps;
//@property (strong,nonatomic) NSString *gs_orderrange;
//@property (nonatomic)NSInteger sp_id;
//@property (nonatomic)NSInteger sp_cgid;
//@property (nonatomic)NSInteger sp_display;
//@property (strong,nonatomic) NSString *sp_name;
//@property (nonatomic)NSInteger sp_city;
//@property (strong,nonatomic) NSString *sp_address;
//@property (strong,nonatomic) NSString *sp_flag;
//@property (strong,nonatomic) NSString *sp_smallpic;
//@property (strong,nonatomic) NSString *sp_bigpic;
//@property (nonatomic) float sp_score;
//@property (strong,nonatomic) NSString *sp_extend;
//@property (nonatomic)NSInteger sp_level;
//@property (nonatomic)NSInteger sp_status;
//@property (strong,nonatomic) NSString *sp_tels;
//@property (strong,nonatomic) NSString *sp_tel;
//@property (nonatomic)NSInteger sp_stare;
//@property (strong,nonatomic) NSString *sp_action;
//@property (nonatomic)NSInteger sp_online;
//@property (nonatomic)NSInteger sp_goodsWeakOpen;
//@property (strong,nonatomic) NSDate * sp_starttime;
//@property (nonatomic)NSInteger cg_fatherid;
//@property (strong,nonatomic) NSString *cg_name;
//@property (strong,nonatomic) NSString *cg_pic;
//@property (strong,nonatomic) NSString *cg_extend;
//@property (nonatomic)NSInteger sp_validdays;
//@property (strong,nonatomic) NSString *sp_goodsRule;
@end